In [19]:
import tensorflow as tf
import numpy as np

Simple TensorFlow exercises.
You should thoroughly test your code

In [23]:
# These functions are to visulize graph inline
from IPython.display import clear_output, Image, display, HTML
def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))

# Questions 

In [2]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))

In [26]:
##############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

# YOUR CODE
tf.reset_default_graph()
x = tf.random_uniform([],minval=-1,maxval=1,dtype=tf.float32)
y = tf.random_uniform([],minval=-1,maxval=1,dtype=tf.float32)
def f1(): return x+y
def f2(): return x-y
def f3(): return 0.0
z = tf.case({tf.less(x,y):f1,tf.greater(x,y):f2},default=f3,exclusive=True)
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs/Assignment1/',sess.graph)
    print(sess.run(z),sess.run(x),sess.run(y))
show_graph(tf.get_default_graph().as_graph_def())

1.61092 0.457503 -0.722933


In [28]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

# YOUR CODE
tf.reset_default_graph()
x = tf.constant([[0,-2,-1],[0,1,2]])
y = tf.zeros_like(x)
out = tf.equal(x,y)
with tf.Session() as sess:
    print(sess.run(out))

[[ True False False]
 [ True False False]]


In [38]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

# YOUR CODE
tf.reset_default_graph()
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])
y=tf.fill(tf.shape(x),30.0)
x_indices_more_than_30 = tf.where(x>30)
x_values_more_than_30 = tf.gather(x,x_indices_more_than_30)
#Graph
with tf.Session() as sess:
    print(sess.run(x_values_more_than_30))

[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [43]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

# YOUR CODE
tf.reset_default_graph()
diagonal_values = tf.range(1,7)
diag = tf.diag(diagonal_values)
with tf.Session() as sess:
    print(sess.run(diag))


[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [48]:

###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

# YOUR CODE
tf.reset_default_graph()
x = tf.random_normal([10,10])
det = tf.matrix_determinant(x)
tf.InteractiveSession()
print(det.eval())


-0.857911


In [55]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

# YOUR CODE
x = tf.constant( [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y = tf.unique(x)

with tf.Session() as sess:
    #y[0] as unique returns unique elemetns and their indices but we only need elements
    print(sess.run(y[0]))

[ 5  2  3 10  6  4  1  0  9]


In [75]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

# YOUR CODE
tf.reset_default_graph()
x = tf.random_normal([300])
y = tf.random_normal([300])
loss = tf.cond( tf.reduce_mean(x-y)<=0, 
                lambda: tf.reduce_sum(tf.square(x-y)),
                lambda: tf.reduce_sum(tf.abs(x-y))
               )
with tf.Session() as sess: 
    print(sess.run(loss))

604.391
