In [149]:
import tensorflow as tf
import numpy as np


Very Important
Always use tf.reset_default_graph() before graph

## Function to show graphs inline

In [140]:
# These functions are to visulize graph inline
from IPython.display import clear_output, Image, display, HTML
def strip_consts(graph_def, max_const_size=32):
    """Strip large constant values from graph_def."""
    strip_def = tf.GraphDef()
    for n0 in graph_def.node:
        n = strip_def.node.add() 
        n.MergeFrom(n0)
        if n.op == 'Const':
            tensor = n.attr['value'].tensor
            size = len(tensor.tensor_content)
            if size > max_const_size:
                tensor.tensor_content = "<stripped %d bytes>"%size
    return strip_def

def show_graph(graph_def, max_const_size=32):
    """Visualize TensorFlow graph."""
    if hasattr(graph_def, 'as_graph_def'):
        graph_def = graph_def.as_graph_def()
    strip_def = strip_consts(graph_def, max_const_size=max_const_size)
    code = """
        <script>
          function load() {{
            document.getElementById("{id}").pbtxt = {data};
          }}
        </script>
        <link rel="import" href="https://tensorboard.appspot.com/tf-graph-basic.build.html" onload=load()>
        <div style="height:600px">
          <tf-graph-basic id="{id}"></tf-graph-basic>
        </div>
    """.format(data=repr(str(strip_def)), id='graph'+str(np.random.rand()))

    iframe = """
        <iframe seamless style="width:1200px;height:620px;border:0" srcdoc="{}"></iframe>
    """.format(code.replace('"', '&quot;'))
    display(HTML(iframe))

## Tensorboard 

In [2]:
#Visulizing with TensorBoard
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b,name='ADDa')
with tf.Session() as sess:
    # For tesorboard
    writer = tf.summary.FileWriter('./graphs',sess.graph)
    print(sess.run(x))
writer.close()    
# use cmd to run following command
# tensorbaord --logdir="./graphs" --port 6006

5


In [151]:
# if we don't name variables name then variables and operations 
#will have default name in graph

#To make graph more readbale with your own names, use following
tf.reset_default_graph()
a = tf.constant(2, name='varA')
b = tf.constant(3, name='varB')
x = tf.add(a,b,name='ADDa')
with tf.Session() as sess:
    # For tesorboard
    writer = tf.summary.FileWriter('./graphs',sess.graph)
    print(sess.run(x))
writer.close() 
show_graph(tf.get_default_graph().as_graph_def())

# use cmd to run following command
# tensorbaord --logdir="./graphs" --port 600

5


In [16]:
# Error due to wrong dimensions
#a = tf.constant(2,shape=[2,2],verify_shape=True)
# Last number is repeated if shape of input is not as given.
a = tf.constant([2,1],shape=[2,2])
#Session to get values rather doing all session thing
session=tf.InteractiveSession()
a.eval()
session.close()

 Try to use tf.constant as minimum as possible as they are 
stored in graph and can case problems. 

## Broadcast

In [ ]:
# Broadcast 
a = tf.constant([2,2],name='a')
b = tf.constant([[0,1],[3,3]],name='b')
x = tf.add(a,b,name='add')
sess = tf.InteractiveSession()
print(x.eval())
sess.close()
# Multiply
y = tf.multiply(a,b)
print(y.eval())

## Initilization of Variables


In [28]:
# Similar to numpy functioanlity 
# Intilization with zeros
zero = tf.zeros([2,3],tf.int32)
print(zero.eval())
# if you have a tensor and want a simiilar tensor of zeros
a_zero = tf.zeros_like(a)
print(a_zero.eval())
# Similar FOR ONES 
one = tf.ones([2,3],tf.float32)
a_one = tf.ones_like(a)
print(one.eval(),a_one.eval())

[[0 0 0]
 [0 0 0]]
[0 0]
[[ 1.  1.  1.]
 [ 1.  1.  1.]] [1 1]


In [42]:
# Create a tensor filled with a value
# tf.fill(dim,value)
# will make tesnor filled with value
# value ==> Scaler
tf.InteractiveSession()
fill = tf.fill([2,3],8)
print(fill.eval())


# Sequences
#tf.linespace(start,stop,num) ==> start,stop ==> float
seq = tf.lin_space(10.0,200.0,4)
print(seq.eval())

#tf.ragne(start,limit=None,detlta=1(stepsize))
# start and go upto limit
rang = tf.range(10,delta=2)
print(rang.eval())

[[8 8 8]
 [8 8 8]]
[  10.           73.33332825  136.66665649  200.        ]
[0 2 4 6 8]


## Sampling from Distributions 

In [53]:
# Randomly Generated Constants
#samples from normal
normal = tf.random_normal([2,2])
print('normal = ',normal.eval())

# If samples are two stdev away, it will resample
trunc_normal = tf.truncated_normal([2,3])
print('normal truncated= ',trunc_normal.eval())

# samples from unifrom distributiono
uniform = tf.random_uniform([2,3])
print('uniform = ',uniform.eval())

# randomly shuffles a matrix in first dimension
# It is not shuffling. Something is wrong here
shuffuled = tf.random_shuffle(uniform)
print('shuffling = ',shuffuled.eval())

#random crop
crop = tf.random_crop(shuffuled,[2,2])
print('Cropped = ',crop.eval())

#
print('multinomial ',tf.multinomial(crop,5).eval())

normal =  [[ 0.19318216  0.93909079]
 [-0.50855142 -0.72119099]]
normal truncated=  [[-1.27935195  0.06305803  1.62826562]
 [-0.53486985 -0.17584486  0.35488561]]
uniform =  [[ 0.12367249  0.46633911  0.65575814]
 [ 0.7016561   0.54130101  0.81774342]]
shuffling =  [[ 0.31032515  0.6522789   0.99679565]
 [ 0.84967387  0.8950851   0.84460962]]
Cropped =  [[ 0.23825634  0.96408808]
 [ 0.51576149  0.87073982]]
[[1 1 0 1 1]
 [1 1 1 1 1]]


In [59]:
# Gamma Distribution
tf.InteractiveSession()
#To have the random numbers same always
tf.set_random_seed(1)
print('Gamma',tf.random_gamma([10],[5,15]).eval())



Gamma [[  6.93326426  10.85909176]
 [  3.97345376  14.96031284]
 [  2.44691014  14.5856781 ]
 [  6.4709301   15.91337585]
 [  7.74565697   9.40691948]
 [  6.34859371  15.63619328]
 [  6.13043451  10.05636597]
 [  4.60282755  15.13726521]
 [  3.75350475   9.64881802]
 [ 10.86459827   9.71612263]]


## Operations and Datatypes 

In [60]:
# Operations
a = tf.constant(4)
b = tf.constant(5)
tf.InteractiveSession()
print(tf.mod(a,b).eval)


<bound method Tensor.eval of <tf.Tensor 'FloorMod:0' shape=() dtype=int32>>


In [67]:
# Datatypes 
# python datatypes are understood
Sess = tf.InteractiveSession()
t_2 = [[True,False,False]]
print(tf.ones_like(t_2).eval())
Sess.close()

#Can give numpy array to tensor operatioins
# Don't use python data types ==> Computationally not good

[[ True  True  True]]


In [136]:
constant = tf.constant(3, name = 'MyConstant')
with tf.Session() as sess:
    #show_graph(tf.get_default_graph().as_graph_def())
    #TB(1)

'tensorboard' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.


In [94]:
# Don't use constant too much. Computationally expensive
aa = tf.Variable([3,2],name='a')

# Variables have many operations on them
# Always first initilze Variables
inti = tf.variables_initializer([aa]) # initilzer only give variables
with tf.Session() as sess:
    print(sess.run(inti))
    # Get default session and run w 
    print(aa.eval())
    print(aa.assign([10,1]).eval())
    print(aa.assign_add([10,1]).eval())
    print(aa.assign_sub([10,1]).eval())
sess.close()
    

None
[3 2]
[10  1]
[20  2]
[10  1]


In [108]:
# Each session keeps its own copy of everything


# NOt good
W = tf.Variable(2)
U = tf.Variable(W*2)
# safe way
# there is some error here.
V = tf.Variable(2*W.intializer)
tf.InteractiveSessioin()
print(V.intializer)
print(V.eval())

AttributeError: 'Variable' object has no attribute 'intializer'

In [ ]:
# Control Dependcies 
a = tf.constant(2)
b = tf.constant()
#this will make sure that a,b,c are already run
tf.Graph.control_dependencies([a,b,c])



## Placeholders 

In [118]:
#PlaceHolders
# If shape=None ==> means any shape
# But be careful as it could be dangerous
# Can be used just as variable or constant
a = tf.placeholder(tf.float32,shape=[3])
b = tf.constant([5,5,5],tf.float32)
c = a+b
with tf.Session() as sess:
    # provide placeholder at run time
    # Other than palceholders can also be fed
    # Can change values of tf.constant or tf.varialbe just as 
    # tf.placeholder
    print(sess.run(c,{a:[1,2,3],b:[3,2,1]}))
    #tf.Graph.is_feedable(b))

[ 4.  4.  4.]


## Lazy Loading  

In [147]:
# Normal loading
tf.reset_default_graph()
x = tf.Variable(10)
y = tf.Variable(5)
z = tf.add(x,y)
with tf.Session() as sess:
    sess.run(tf.variables_initializer([x,y]))
    wiriter = tf.summary.FileWriter('./my_graph/lec2',sess.graph)
    for _ in range(10):
        sess.run(z)
    writer.close()
    show_graph(tf.get_default_graph().as_graph_def())

In [148]:
# Lazy loading
# Problem 
tf.reset_default_graph()
x = tf.Variable(10)
y = tf.Variable(5)
with tf.Session() as sess:
    sess.run(tf.variables_initializer([x,y]))
    wiriter = tf.summary.FileWriter('./my_graph/lec2',sess.graph)
    for _ in range(10):
        # Use op while run
        # You will have multiple add nodes in this case
        # It will make multiple nodes in graph
        sess.run(tf.add(x,y))
        writer.close()  
    show_graph(tf.get_default_graph().as_graph_def())